const SERVER_BASE_URL = 'http://localhost:5000/api/v1';
const THEBOOKSTORE_THEME_VARIANT = 'THEBOOKSTORE_THEME_VARIANT';
const THEBOOKSTORE_AUTH_TOKEN = 'THEBOOKSTORE_AUTH_TOKEN';
const THEBOOKSTORE_AUTH_DATA = 'THEBOOKSTORE_AUTH_DATA';
const THEBOOKSTORE_VIEW_MODE = 'THEBOOKSTORE_VIEW_MODE';

export const CONSTANTS = {SERVER_BASE_URL, THEBOOKSTORE_THEME_VARIANT, THEBOOKSTORE_AUTH_TOKEN, THEBOOKSTORE_AUTH_DATA, THEBOOKSTORE_VIEW_MODE};